---
- name: create a new primary partition
  hosts: dev
  tasks:
    - name: print the error message if /dev/sdb does not exit
      debug:
        msg: Disk does not exist
        when: ansible_devices.vdb is undefined
    - name: create a partition of size 1000Mib
      block:
        - name: Create a new primary partition with a size of 10000MiB
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 10000MiB
          when: ansible_devices.sdb is defined
      rescue:
        - name: print the error message if /dev/sdb has insuficient disk space
          debug:
            msg: Could not create partition of that size
        - name: Create a new primary partition with a size of 500MiB
          parted:
            device: /dev/sdb
            number: 1
            state: present
            part_end: 500MiB
- name: Create a filesystem and mount up device
  hosts: dev
  tasks:
    - name: Create a ext4 filesystem on /dev/sdb1 and check disk blocks
      filesystem:
        fstype: ext4
        dev: /dev/sdb1
      when: ansible_devices.vdb.partitions.sdb1 is defined
    - name: Mount up device
      mount:
        path: /newpart
        src: /dev/sdb1
        fstype: ext4
        opts: noatime
        state: mounted
      when: ansible_devices.vdb.partitions.sdb1 is defined