---
- name: save hosts info
  hosts:  all
  tasks:
    - name: Download file from a file path
      get_url:
        url:  http://192.168.3.180:8929/test01/ansible-playbook/-/raw/master/templatefile/hwreport.empty?inline=false
        dest: /var/www/html/hwreport.index
        force: True
    - name: replace hostname
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^hostname=.*'
        replace: 'hostname={{ ansible_hostname }}'
    - name: replace memory
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^memory=.*'
        replace: "memory={{ ansible_memory_mb.real.total }}"
    - name: replace ansible_bios_version
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^bios_version=.*'
        replace: 'bios_version={{ ansible_bios_version }}'
    - name: replace sda_size
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^sda_size=.*'
        replace: 'sda_size={{ ansible_devices.sda.size}}'
      when: ansible_devices.sda.size is defined
    - name: replace sdb_size
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^sdb_size=.*'
        replace: 'sdb_size={{ ansible_devices.sdb.size}}'
      when: ansible_devices.sdb.size is defined
    - name: replace sda_size if /dev/sda is undefined
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^sda_size=.*'
        replace: 'sda_size=NONE'
      when: ansible_devices.sda.size is undefined
    - name: replace sdb_size if /dev/sdb is undefined
      replace:
        path: /var/www/html/hwreport.index
        regexp: '^sdb_size=.*'
        replace: 'sdb_size=NONE'
      when: ansible_devices.sdb.size is undefined
