---
- name: install MariaDB
  hosts: all
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
          - mariadb
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: yes 
        state: started
    - name: config firewalld for mariadb service
      firewalld:
        service: mysql
        permanent: yes
        state: enabled
        immediate: yes
