---
- name: install zabbix agent
  hosts: all
  tasks:
    - name: install zabbix yum repo
      command: "curl https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-4.el8.noarch.rpm -o /tmp/zabbix-release-6.0-4.el8.noarch.rpm"
    - name: install yum repo
      command: rpm -Uvh /tmp/zabbix-release-6.0-4.el8.noarch.rpm
    - name: install agent
      command: "dnf install zabbix-agent -y"
    - name: edit config file
      template:
        src:  zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        force: True
    - name: enable agent and start 
      service:
        name: zabbix-agent
        state: started
        enabled: yes